### ISSUE TITLE
Copper Ore not outputting 2x

### ISSUE THREAD

**Issue by wot902809** [Cazadorsniper/Furnace-Overhaul#10]
Copper Ore (Actually all ores) from Modern Warfare mod 1.12.2 does not double out using the ore processing upgrade. Wondering would it be possible for you to implement this mod to work for yours. Thank you.
I downloaded 1.12.2 mod from server 1 at the very bottom of this webpage. http://www.9minecraft.net/modern-warfare-mod/

**Comment by Cazadorsniper** [comment]
Yeah... Don't download mods from 9Minecraft always download them from the mod devs website or CurseForge.

Also Copper Ore from Thermal Foundation doubles fine.
