### ISSUE TITLE
Furnace Issues

### ISSUE THREAD

**Issue by Cazadorsniper** [Cazadorsniper/Furnace-Overhaul#12]
- [x] Can't shift+right-click upgrades into upgrade slots
- [x] Furnaces change directions when exiting and re-entering the world in 2 directions
- [x] Energy buffer in the GUI isn't completely full (probably my fault on that one)
- [ ] TOP and Hwyla Integration
- [x] The furnaces do not properly turn "on" when using electric upgrade.

**Comment by Cazadorsniper** [comment]
Upgrades shift-click into the input slot before going into the Upgrade slots

**Comment by Shadows-of-Fire** [comment]
I'll lock that slot to furnace inputs only, which should resolve that
