### ISSUE TITLE
Both Processing Upgrades

### ISSUE THREAD

**Issue by Cazadorsniper** [Cazadorsniper/Furnace-Overhaul#13]
Although I believe I "maybe" able to fix this myself:

- [x] Ore Processing Upgrade should only work on specific blocks that are already specified and ores like iron ore, diamond ore aluminum/aluminium ore

- [ ] Processing Upgrade should not be able to double the results of the Ore Processing Upgrade.

**Comment by Shadows-of-Fire** [comment]
#1 here isn't actually a thing, only the processing upgrade actively doubles everything.
(The Ore Processing upgrade already functions properly).

**Comment by Cazadorsniper** [comment]
Got reports that the Ore Processing upgrade works on ore dusts too like iron dust, gold dust and etc.

**Comment by Shadows-of-Fire** [comment]
Unless those dusts also have the `oreX` tag on them, that's not possible.  Or the user is confusing it with the processing upgrade.
