### ISSUE TITLE
Ore processing upgrade recipe?

### ISSUE THREAD

**Issue by MindGamesMcClane** [Cazadorsniper/Furnace-Overhaul#2]
I'm playing project ozone lite and there's no recipe for the ore processing upgrade, I've looked online for a recipe because maybe NEI is having a problem since there's no golden bag of holding but you can get them. If I could get a link to a recipe or a resolution that would be great! Thanks :)

**Comment by Cazadorsniper** [comment]
Not a single upgrade works in 1.10.2.
