### ISSUE TITLE
Furnace Dupe Bug

### ISSUE THREAD

**Issue by focamacho** [Cazadorsniper/Furnace-Overhaul#25]
1 - Put some items inside a Furnace
2 - Keep the GUI open
3 - Break the Furnace using a block breaker, golem, or just tells another player to break it for you
4 - Take the items from the GUI and from the ground
5 - See the video for more info

(GUI don't close when the Furnace is broken, that's the problem)

Video: https://www.youtube.com/watch?v=TJL-NVNl2lc

**Comment by gswindle76** [comment]
Also, Duplicates last cooked Item with netherrack ( if netherrack smelt is disabled through mods).
