### ISSUE TITLE
Create anything with Chiseled Cobble

### ISSUE THREAD

**Issue by Drazuam** [Cazadorsniper/Furnace-Overhaul#26]
There is a glitch where chiseled cobblestone can be swapped in for a currently smelting item, and the furnace will continue to create whatever was previously queued up.

1. put in two items (i.e. insert two iron ore into furnace)
2. wait for one ore to smelt
3. swap a stack of chiseled cobblestone (i.e. Cobblestone: Big Tile) for the single ore block that is currently being smelted
4. watch as the cobblestone is smelted into ingots

Version is 2.2.0, Modpack is Project Ozone 3 Kappa, version 3.2.52

**Comment by Cazadorsniper** [comment]
I know
