### ISSUE TITLE
Zenith furnace periodically "disconnects" from Thermal Foundation itemducts

### ISSUE THREAD

**Issue by zzBuilderzz** [Cazadorsniper/Furnace-Overhaul#3]
Every so often the furnace refuses to accept importation and exportation of resources. I'm trying automate the smelting of draconic dust into draconic ingots. This is temporarily fixed by removing and replacing servos on the itemducts. the itemducts still connect but no items flow through them to furnace

**Comment by Cazadorsniper** [comment]
Hopefully this is fixed next update.
