### ISSUE TITLE
Hello there

### ISSUE THREAD

**Issue by Milliath** [Cazadorsniper/Furnace-Overhaul#6]
Issue: You lose the installed upgrades upon breaking a furnace;
Suggestion: more output slots for latter furnaces.
Thanks :)

**Comment by Cazadorsniper** [comment]
I know and the suggestion will not happen to current furnaces, however I'm thinking of adding a new furnace with several input and output slots.

**Comment by TheDeviantCrafter** [comment]
Furnaces still lose their inventory when broken. Can this issue be reopened?

**Comment by Cazadorsniper** [comment]
No, it taking a long time to get the mod updated because of what I'm trying to do and PO3.

**Comment by TheDeviantCrafter** [comment]
It doesn't need to be fixed immediately, or even this year, to be worth keeping the issue open.
